name: trt_llm_rag
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - conda-forge::openmpi
  - conda-forge::mpi4py
  - pip
  - pip:
    - fire
    - httpx
    - websockets
    - matplotlib
    - tensorrt_llm
    - --extra-index-url https://pypi.nvidia.com
